### ISSUE TITLE
Gnomerunner broken on seamonkey 2.32.1

### ISSUE THREAD

**Issue by pevsner** [Exalm/gnomerunnergtk-revived#8]
Unfortunately it seems not to be incompatible with seamonkey 2.32.1.
Any chance it'll be updated to work. Thanks in advance

**Comment by dilworks** [comment]
Seamonkey 2.32.1 (yes, a POINT bugfix release) somehow broke compatibilty with pretty much ALL SM-specific themes (at least all on AMO).

However, it seems that only the version check is borked - if you use something to override compatibilty checks ([like this](https://addons.mozilla.org/en-us/seamonkey/addon/checkcompatibility/)), the affected themes will work just fine.

**Comment by Exalm** [comment]
Yes, that's just a version number change. The theme has max version set as 2.32.0, I'll update it now. I wish SM had extensions compatible by default, since it's developed very slowly.

**Comment by Exalm** [comment]
Fixed.

**Comment by dumol** [comment]
Thank you! I had the same problem…

**Comment by pevsner** [comment]
Excellent, thanks Exalm, a nifty looking seamonkey again
