### ISSUE TITLE
Global theme

### ISSUE THREAD

**Issue by Israel-** [Exalm/gnomerunnergtk-revived#9]
Hi,
I would like to install this theme to be the global default (all users).  Is this possible?
I am using GNU/Linux, but even if you have the solution for another platform it will give me a starting place

**Comment by Exalm** [comment]
Hello. I don't know any ways to do this, and this is not relevant to this particular (or any other) theme anyway. ;)

**Comment by Israel-** [comment]
Well... I wanted to use your theme as the default for all users on the OS.  So i thought it was pertinent to your theme.  I will just use the /etc/skel method... thanks for your time
